source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JBLoginDataCommands_Example', :exclusive => true do
  pod "JBLoginDataCommands", :path => "../"
end

target 'JBLoginDataCommands_Tests', :exclusive => true do
  pod "JBLoginDataCommands", :path => "../"

  pod 'Kiwi'
end
