source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JBLoginDataCommands_Example' do
  pod "JBLoginDataCommands", :path => "../"
end

target 'JBLoginDataCommands_Tests' do
  pod "JBLoginDataCommands", :path => "../"

  pod 'Kiwi'
end
